name:                cmruncc
version:             0.1.0.0
github:              "wojtex/cmruncc"
license:             BSD3
author:              "Wojciech Kordalski"
maintainer:          "kordalski.wojciech@gmail.com"
copyright:           "2020 Wojciech Kordalski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wkordalski/cmruncc#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - msgpack
    - bytestring
    - network
    - transformers
    - vector
    - text
    - zstd

executables:
  cmruncc-sched:
    main:                Main.hs
    source-dirs:         sched
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmruncc
    - aeson
    - bytestring
    - containers
    - msgpack
    - network
    - yaml
  cmruncc-builder:
    main:                Main.hs
    source-dirs:         builder
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmruncc
    - aeson
    - bytestring
    - filepath
    - mtl
    - network
    - process
    - text
    - yaml
  cmruncc-runner:
    main:                Main.hs
    source-dirs:         runner
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmruncc
    - aeson
    - base16-bytestring
    - bytestring
    - filepath
    - mtl
    - network
    - posix-pty
    - process
    - temporary
    - text
    - yaml

tests:
  cmruncc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmruncc
